[build]
  base    = "homigo"       
  command = "npm install && npm install bcrypt && npm install -D tailwindcss postcss autoprefixer @tailwindcss/postcss && npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
