[build]
  base    = "homigo"       
  command = "npm install && npm install bcrypt && npm install -D tailwindcss postcss autoprefixer @tailwindcss/postcss && npm run build"
  publish = "homigo/.next"

[[rewrites]]
  from = "/*"
  to = "/:splat"
  status = 200
